# 海澜之家 V1.2
## 91Panda 制作 2025-2-16
## 适用于青楼之王0.3版本



init 900 python:


    config.label_overrides["init_items"] = "Panda_init_items"

    HLAGROUP_template = Mod(
        
                ## Basic mod information (Important: Version is used to check for new versions of the mod. Failure to update the version number may lead to broken mods and saved games)
                name = "海澜之家",
                folder = "HLA GROUP",
                creator = "PANDA",
                version = 1.2,
                pic = "海澜之家封面.png",
                description = """神秘的服装商来到了泽恩拓展业务。他带来了质量更好，价格也更贵的各类新品衣物。\n海澜之家，每年逛2次，每次都有新发现！""",

                ## Event dictionary (all mod events must be declared here)
                )
    # 添加新的 Item  

label Panda_init_items():
    # Each item exists only once as an Item object. Copies used in-game are instances of the ItemInstance object.

    python:


        # REGULAR ITEMS #

        all_items = [
                    Item(name = _('Short sword'), target = 'MC', type = IT_Weapon, pic = 'Short sword.webp', rank = 1, rarity = 1, price = 250, effects = (Effect('change', 'strength', 1), ), description =__(  "")),
                    Item(name = _('Cutlass'), target = 'MC', type = IT_Weapon, pic = 'Cutlass.webp', rank = 1, rarity = 2, price = 500, effects = (Effect('change', 'strength', 2), ), description =__(  "It's not a knife. That's a knife.")),
                    Item(name = _('Axe'), target = 'MC', type = IT_Weapon, pic = 'Axe.webp', rank = 2, rarity = 2, price = 1000, effects = (Effect('change', 'strength', 2), Effect('change', 'spirit', 1), ), description =__(  "")),
                    Item(name = _('Lance'), target = 'MC', type = IT_Weapon, pic = 'Lance.webp', rank = 2, rarity = 2, price = 2500, effects = (Effect('change', 'strength', 3), Effect('change', 'charisma', 1), ), description =__(  "")),
                    Item(name = _('Long sword'), target = 'MC', type = IT_Weapon, pic = 'Long sword.webp', rank = 2, rarity = 3, price = 3500, effects = (Effect('change', 'strength', 3), Effect('change', 'charisma', 1), Effect('change', 'spirit', 1), ), description =__(  "")),
                    Item(name = _('Rapier'), target = 'MC', type = IT_Weapon, pic = 'Rapier.webp', rank = 3, rarity = 3, price = 5000, effects = (Effect('change', 'strength', 4), Effect('change', 'charisma', 2), ), description =__(  "")),
                    Item(name = _('Battle axe'), target = 'MC', type = IT_Weapon, pic = 'Battle axe.webp', rank = 3, rarity = 3, price = 10000, effects = (Effect('change', 'strength', 5), Effect('change', 'spirit', 2), ), description =__(  "")),
                    Item(name = _('Warhammer'), target = 'MC', type = IT_Weapon, pic = 'Warhammer.webp', rank = 3, rarity = 4, price = 17500, effects = (Effect('change', 'strength', 5), Effect('change', 'charisma', 2), Effect('change', 'spirit', 1), ), description =__(  "")),
                    Item(name = _('Holy sword'), target = 'MC', type = IT_Weapon, pic = 'Holy sword.webp', rank = 4, rarity = "U", price = 40000, effects = (Effect('change', 'strength', 6), Effect('change', 'spirit', 3), ), description =__(  "This sword hums with power. The light reflects so brightly on its blade it could blind the angels themselves.")),
                    Item(name = _('Demon sword'), target = 'MC', type = IT_Weapon, pic = 'Demon sword.webp', rank = 4, rarity = "S", price = 100000, effects = (Effect('change', 'strength', 8), Effect('change', 'charisma', 4), Effect('change', 'spirit', -2), ), description =__(  "The blade pulses with the dark fury of the demon trapped inside. They say he devours every poor soul that gets slain by this blade.")),
                    Item(name = _('Broom staff'), target = 'MC', type = IT_Weapon, pic = 'Broom staff.webp', rank = 1, rarity = 1, price = 250, effects = (Effect('change', 'spirit', 1), ), description =__(  "")),
                    Item(name = _('Wooden staff'), target = 'MC', type = IT_Weapon, pic = 'Wooden staff.webp', rank = 1, rarity = 2, price = 500, effects = (Effect('change', 'spirit', 2), ), description =__(  "")),
                    Item(name = _('Goblin staff'), target = 'MC', type = IT_Weapon, pic = 'Goblin staff.webp', rank = 2, rarity = 2, price = 1000, effects = (Effect('change', 'charisma', 1), Effect('change', 'spirit', 2), ), description =__(  "")),
                    Item(name = _('Bronze staff'), target = 'MC', type = IT_Weapon, pic = 'Bronze staff.webp', rank = 2, rarity = 2, price = 2500, effects = (Effect('change', 'strength', 1), Effect('change', 'spirit', 3), ), description =__(  "")),
                    Item(name = _('Wind staff'), target = 'MC', type = IT_Weapon, pic = 'Wind staff.webp', rank = 2, rarity = 3, price = 3500, effects = (Effect('change', 'strength', 1), Effect('change', 'charisma', 1), Effect('change', 'spirit', 3), ), description =__(  "")),
                    Item(name = _('Healing staff'), target = 'MC', type = IT_Weapon, pic = 'Healing staff.webp', rank = 3, rarity = 3, price = 5000, effects = (Effect('change', 'charisma', 2), Effect('change', 'spirit', 4), ), description =__(  "")),
                    Item(name = _('Thunder staff'), target = 'MC', type = IT_Weapon, pic = 'Thunder staff.webp', rank = 3, rarity = 3, price = 10000, effects = (Effect('change', 'strength', 2), Effect('change', 'spirit', 5), ), description =__(  "")),
                    Item(name = _('Emerald staff'), target = 'MC', type = IT_Weapon, pic = 'Emerald staff.webp', rank = 3, rarity = 4, price = 17500, effects = (Effect('change', 'strength', 1), Effect('change', 'charisma', 2), Effect('change', 'spirit', 5), ), description =__(  "")),
                    Item(name = _('Crystal staff'), target = 'MC', type = IT_Weapon, pic = 'Crystal staff.webp', rank = 4, rarity = 4, price = 40000, effects = (Effect('change', 'strength', 3), Effect('change', 'spirit', 6), ), description =__(  "")),
                    Item(name = _('Angel staff'), target = 'MC', type = IT_Weapon, pic = 'Angel staff.webp', rank = 4, rarity = 5, price = 100000, effects = (Effect('change', 'charisma', 2), Effect('change', 'spirit', 8), ), description =__(  "")),
                    Item(name = _('Throwing knife'), target = 'MC', type = IT_Weapon, pic = 'Throwing knife.webp', rank = 1, rarity = 1, price = 250, effects = (Effect('change', 'charisma', 1), ), description =__(  "")),
                    Item(name = _('Throwing axe'), target = 'MC', type = IT_Weapon, pic = 'Throwing axe.webp', rank = 1, rarity = 2, price = 500, effects = (Effect('change', 'charisma', 2), ), description =__(  "")),
                    Item(name = _('Bow'), target = 'MC', type = IT_Weapon, pic = 'Bow.webp', rank = 2, rarity = 2, price = 1000, effects = (Effect('change', 'strength', 1), Effect('change', 'charisma', 2), ), description =__(  "")),
                    Item(name = _('Ornate bow'), target = 'MC', type = IT_Weapon, pic = 'Ornate bow.webp', rank = 2, rarity = 2, price = 2500, effects = (Effect('change', 'charisma', 3), Effect('change', 'spirit', 1), ), description =__(  "")),
                    Item(name = _('Flintlock'), target = 'MC', type = IT_Weapon, pic = 'Flintlock.webp', rank = 2, rarity = 3, price = 3500, effects = (Effect('change', 'strength', 2), Effect('change', 'charisma', 3), ), description =__(  "")),
                    Item(name = _('Crossbow'), target = 'MC', type = IT_Weapon, pic = 'Crossbow.webp', rank = 3, rarity = 3, price = 5000, effects = (Effect('change', 'strength', 1), Effect('change', 'charisma', 4), Effect('change', 'spirit', 1), ), description =__(  "")),
                    Item(name = _('Repeater'), target = 'MC', type = IT_Weapon, pic = 'Repeater.webp', rank = 3, rarity = 3, price = 10000, effects = (Effect('change', 'strength', 2), Effect('change', 'charisma', 5), ), description =__(  "")),
                    Item(name = _('Blunderbuss'), target = 'MC', type = IT_Weapon, pic = 'Blunderbuss.webp', rank = 3, rarity = 4, price = 17500, effects = (Effect('change', 'strength', 3), Effect('change', 'charisma', 5), ), description =__("This. Is. My boomstick!")),
                    Item(name = _('Holy handgrenade'), target = 'MC', type = IT_Weapon, pic = 'Holy handgrenade.webp', rank = 4, rarity = 4, price = 40000, effects = (Effect('change', 'charisma', 6), Effect('change', 'spirit', 3), ), description =__(  "")),
                    Item(name = _('Death dispenser'), target = 'MC', type = IT_Weapon, pic = 'Death dispenser.webp', rank = 4, rarity = 5, price = 100000, effects = (Effect('change', 'strength', 4), Effect('change', 'charisma', 8), Effect('change', 'spirit', -2), ), description =__(  "")),
                    Item(name = _('Arios amulet'), target = 'MC', type = IT_Necklace, pic = 'Arios amulet.webp', rank = 1, rarity = "U", price = 25000, effects = (), description =__("Unique reward for completing the Arios knight quest.")),
                    Item(name = _('Shalia talisman'), target = 'MC', type = IT_Necklace, pic = 'Shalia talisman.webp', rank = 1, rarity = "U", price = 25000, effects = (), description =__("Unique reward for completing the Shalia shadow quest.")),
                    Item(name = _('Merchant sigil'), target = 'MC', type = IT_Necklace, pic = 'Merchant sigil.webp', rank = 1, rarity = "U", price = 25000, effects = (), description =__("Unique reward for completing the guild of merchants quest.")),
                    Item(name = _('Fur boots'), target = 'MC', type = IT_Accessory, pic = 'Fur boots.webp', rank = 1, rarity = 1, price = 500, effects = (Effect('change', 'speed', 1), ), ),
                    Item(name = _('Leather boots'), target = 'MC', type = IT_Accessory, pic = 'Leather boots.webp', rank = 1, rarity = 2, price = 2000, effects = (Effect('change', 'speed', 2), ), ),
                    Item(name = _('Elven boots'), target = 'MC', type = IT_Accessory, pic = 'Elven boots.webp', rank = 2, rarity = 3, price = 10000, effects = (Effect('change', 'speed', 3), ), ),
                    Item(name = _('Horse'), target = 'MC', type = IT_Accessory, pic = 'Horse.webp', rank = 3, rarity = 4, price = 50000, effects = (Effect('change', 'speed', 4), ), ),
                    Item(name = _('Dark horse'), target = 'MC', type = IT_Accessory, pic = 'Dark horse.webp', rank = 4, rarity = 5, price = 150000, effects = (Effect('change', 'speed', 5), ), ),
                    Item(name = _('Dragon egg'), target = 'MC', type = IT_Misc, pic = 'Dragon egg.webp', rank = 1, rarity = "S", charges = 1, price = 5000, effects = (Effect('gain', 'skill points', 1), ), description =__(  "'He was no dragon...'\nEat this at your own risk!"), sound = "crunch.ogg", hidden_effect = True),
                    Item(name = _('Knuckle duster'), target = 'girl', type = IT_Weapon, pic = 'Knuckle duster.webp', rank = 1, rarity = 1, price = 50, effects = (Effect('change', 'defense', 1), ), ),
                    Item(name = _('Hook'), target = 'girl', type = IT_Weapon, pic = 'Hook.webp', rank = 1, rarity = 1, price = 250, effects = (Effect('change', 'defense', 2), ), ),
                    Item(name = _('Shiv'), target = 'girl', type = IT_Weapon, pic = 'Shiv.webp', rank = 1, rarity = 2, price = 500, effects = (Effect('change', 'defense', 3), ), ),
                    Item(name = _('Knife'), target = 'girl', type = IT_Weapon, pic = 'Knife.webp', rank = 2, rarity = 2, price = 1000, effects = (Effect('change', 'defense', 4), ), ),
                    Item(name = _('Dagger'), target = 'girl', type = IT_Weapon, pic = 'Dagger.webp', rank = 2, rarity = 2, price = 1750, effects = (Effect('change', 'defense', 5), ), ),
                    Item(name = _('Sacrificial knife'), target = 'girl', type = IT_Weapon, pic = 'Sacrificial knife.webp', rank = 2, rarity = 3, price = 2750, effects = (Effect('change', 'defense', 6), ), ),
                    Item(name = _('Mace'), target = 'girl', type = IT_Weapon, pic = 'Mace.webp', rank = 3, rarity = 3, price = 5000, effects = (Effect('change', 'defense', 7), ), ),
                    Item(name = _('Whip'), target = 'girl', type = IT_Weapon, pic = 'Whip.webp', rank = 3, rarity = 4, price = 10000, effects = (Effect('change', 'defense', 8), ), ),
                    Item(name = _('Steel whip'), target = 'girl', type = IT_Weapon, pic = 'Steel whip.webp', rank = 4, rarity = 4, price = 25000, effects = (Effect('change', 'defense', 9), ), ),
                    Item(name = _('Magic blade'), target = 'girl', type = IT_Weapon, pic = 'Magic blade.webp', rank = 4, rarity = 5, price = 60000, effects = (Effect('change', 'defense', 10), ), ),
                    Item(name = _('Dildo'), target = 'girl', type = IT_Toy, pic = 'Dildo.webp', rank = 1, rarity = 2, charges = 8, price = 125, effects = (Effect('gain', 'sex', 1, 0.5), ), description =__("Chance to improve Sex when resting (limited uses).")),
                    Item(name = _('XL dildo'), target = 'girl', type = IT_Toy, pic = 'XL dildo.webp', rank = 2, rarity = 3, charges = 8, price = 500, effects = (Effect('gain', 'sex', 2, 0.5), ), description =__("Chance to improve Sex when resting (limited uses).")),
                    Item(name = _('XXL dildo'), target = 'girl', type = IT_Toy, pic = 'XXL dildo.webp', rank = 3, rarity = 4, charges = 8, price = 2500, effects = (Effect('gain', 'sex', 3, 0.5), ), description =__("Chance to improve Sex when resting (limited uses).")),
                    Item(name = _('Black dildo'), target = 'girl', type = IT_Toy, pic = 'Black dildo.webp', rank = 4, rarity = 5, charges = 8, price = 10000, effects = (Effect('gain', 'sex', 5, 0.5), ), description =__("Chance to improve Sex when resting (limited uses).")),
                    Item(name = _('Butt plug'), target = 'girl', type = IT_Toy, pic = 'Butt plug.webp', rank = 1, rarity = 2, charges = 8, price = 125, effects = (Effect('gain', 'anal', 1, 0.5), ), description =__("Chance to improve Anal when resting (limited uses).")),
                    Item(name = _('Butt pump'), target = 'girl', type = IT_Toy, pic = 'Butt pump.webp', rank = 2, rarity = 3, charges = 8, price = 500, effects = (Effect('gain', 'anal', 2, 0.5), ), description =__("Chance to improve Anal when resting (limited uses).")),
                    Item(name = _('Anal dildo'), target = 'girl', type = IT_Toy, pic = 'Anal dildo.webp', rank = 3, rarity = 4, charges = 8, price = 2500, effects = (Effect('gain', 'anal', 3, 0.5), ), description =__("Chance to improve Anal when resting (limited uses).")),
                    Item(name = _('Anal beads'), target = 'girl', type = IT_Toy, pic = 'Anal beads.webp', rank = 4, rarity = 5, charges = 8, price = 10000, effects = (Effect('gain', 'anal', 5, 0.5), ), description =__("Chance to improve Anal when resting (limited uses).")),
                    Item(name = _('Ropes'), target = 'girl', type = IT_Toy, pic = 'Ropes.webp', rank = 1, rarity = 2, charges = 8, price = 125, effects = (Effect('gain', 'fetish', 1, 0.5), ), description =__("Chance to improve Fetish when resting (limited uses).")),
                    Item(name = _('Cuffs'), target = 'girl', type = IT_Toy, pic = 'Cuffs.webp', rank = 2, rarity = 3, charges = 8, price = 500, effects = (Effect('gain', 'fetish', 2, 0.5), ), description =__("Chance to improve Fetish when resting (limited uses).")),
                    Item(name = _('Gag'), target = 'girl', type = IT_Toy, pic = 'Gag.webp', rank = 3, rarity = 4, charges = 8, price = 2500, effects = (Effect('gain', 'fetish', 3, 0.5), ), description =__("Chance to improve Fetish when resting (limited uses).")),
                    Item(name = _('Blindfold'), target = 'girl', type = IT_Toy, pic = 'Blindfold.webp', rank = 4, rarity = 5, charges = 8, price = 10000, effects = (Effect('gain', 'fetish', 5, 0.5), ), description =__("Chance to improve Fetish when resting (limited uses).")),
                    Item(name = _('Arousing gel'), target = 'girl', type = IT_Toy, pic = 'Arousing gel.webp', rank = 1, rarity = 2, charges = 8, price = 125, effects = (Effect('gain', 'service', 1, 0.5), ), description =__("Chance to improve Service when resting (limited uses).")),
                    Item(name = _('Egg vibrator'), target = 'girl', type = IT_Toy, pic = 'Egg vibrator.webp', rank = 2, rarity = 3, charges = 8, price = 500, effects = (Effect('gain', 'service', 2, 0.5), ), description =__("Chance to improve Service when resting (limited uses).")),
                    Item(name = _('Long vibrator'), target = 'girl', type = IT_Toy, pic = 'Long vibrator.webp', rank = 3, rarity = 4, charges = 8, price = 2500, effects = (Effect('gain', 'service', 3, 0.5), ), description =__("Chance to improve Service when resting (limited uses).")),
                    Item(name = _('Arcanic vibrator'), target = 'girl', type = IT_Toy, pic = 'Arcanic vibrator.webp', rank = 4, rarity = 5, charges = 8, price = 10000, effects = (Effect('gain', 'service', 5, 0.5), ), description =__("Chance to improve Service when resting (limited uses).")),
                    Item(name = _('Lucky charm'), target = 'girl', type = IT_Necklace, pic = 'Lucky charm.webp', rank = 1, rarity = 2, price = 1250, effects = (Effect('special', 'lucky', 1), ), description =__("It is said to bring luck to its owner. The rabbit it belonged to might disagree...")),
                    Item(name = _('Leather choker'), target = 'girl', type = IT_Necklace, pic = 'Leather choker.webp', rank = 1, rarity = 2, price = 750, effects = (Effect('boost', 'obedience tests', 0.2), ), ),
                    Item(name = _('Bronze amulet'), target = 'girl', type = IT_Necklace, pic = 'Bronze amulet.webp', rank = 2, rarity = 3, price = 2500, effects = (Effect('boost', 'all regular skills gains', 0.05), ), ),
                    Item(name = _('Silver amulet'), target = 'girl', type = IT_Necklace, pic = 'Silver amulet.webp', rank = 3, rarity = 4, price = 12500, effects = (Effect('boost', 'all regular skills gains', 0.1), ), ),
                    Item(name = _('Gold amulet'), target = 'girl', type = IT_Necklace, pic = 'Gold amulet.webp', rank = 4, rarity = 5, price = 25000, effects = (Effect('boost', 'all regular skills gains', 0.15), ), ),
                    Item(name = _('Monster pearl necklace'), target = 'girl', type = IT_Necklace, pic = 'Monster pearl necklace.webp', rank = 3, rarity = 5, price = 25000, effects = (Effect('boost', 'all sex skills gains', 0.1), ), description =__(  "It came from the sea...")),
                    Item(name = _('Ale'), target = 'girl', type = IT_Supplies, pic = 'Ale.webp', rank = 1, rarity = 1, charges = 10, price = 500, effects = (Effect('change', 'waitress results', 1), ), description =__(  "Used when working.")),
                    Item(name = _('Massage oil'), target = 'girl', type = IT_Supplies, pic = 'Massage oil.webp', rank = 1, rarity = 1, charges = 10, price = 500, effects = (Effect('change', 'masseuse results', 1), ), description =__(  "Used when working.")),
                    Item(name = _('Tanning oil'), target = 'girl', type = IT_Supplies, pic = 'Tanning oil.webp', rank = 1, rarity = 1, charges = 10, price = 500, effects = (Effect('change', 'dancer results', 1), ), description =__(  "Used when working.")),
                    Item(name = _('Fans'), target = 'girl', type = IT_Supplies, pic = 'Fans.webp', rank = 1, rarity = 1, charges = 10, price = 500, effects = (Effect('change', 'geisha results', 1), ), description =__(  "Used when working.")),
                    Item(name = _('Sensual perfume'), target = 'girl', type = IT_Supplies, pic = 'Sensual perfume.webp', rank = 1, rarity = 3, charges = 10, price = 750, effects = (Effect('change', 'service results', 1), ), description =__(  "Used when working.")),
                    Item(name = _('Gel'), target = 'girl', type = IT_Supplies, pic = 'Gel.webp', rank = 1, rarity = 3, charges = 10, price = 750, effects = (Effect('change', 'sex results', 1), ), description =__(  "Used when working.")),
                    Item(name = _('Enema'), target = 'girl', type = IT_Supplies, pic = 'Enema.webp', rank = 1, rarity = 3, charges = 10, price = 750, effects = (Effect('change', 'anal results', 1), ), description =__(  "Used when working.")),
                    Item(name = _('Wax'), target = 'girl', type = IT_Supplies, pic = 'Wax.webp', rank = 1, rarity = 3, charges = 10, price = 750, effects = (Effect('change', 'fetish results', 1), ), description =__(  "Used when working.")),
                    Item(name = _('Glasses'), target = 'girl', type = IT_Accessory, pic = 'Glasses.webp', rank = 1, rarity = 3, price = 1000, effects = (Effect('boost', 'xp gains', 0.1), ), ),
                    Item(name = _('Tail'), target = 'girl', type = IT_Accessory, pic = 'Tail.webp', rank = 1, rarity = 3, price = 1000, effects = (Effect('boost', 'reputation gains', 0.2), ), ),
                    Item(name = _('Bunny ears'), target = 'girl', type = IT_Accessory, pic = 'Bunny ears.webp', rank = 1, rarity = 4, price = 2500, effects = (Effect('change', 'waitress results', 1), ), ),
                    Item(name = _('Hairpin'), target = 'girl', type = IT_Accessory, pic = 'Hairpin.webp', rank = 1, rarity = 4, price = 2500, effects = (Effect('change', 'masseuse results', 1), ), ),
                    Item(name = _('Nun veil'), target = 'girl', type = IT_Accessory, pic = 'Nun veil.webp', rank = 1, rarity = 4, price = 2500, effects = (Effect('change', 'dancer results', 1), ), ),
                    Item(name = _('Noh mask'), target = 'girl', type = IT_Accessory, pic = 'Noh mask.webp', rank = 1, rarity = 4, price = 2500, effects = (Effect('change', 'geisha results', 1), ), ),
                    Item(name = _('Cat ears'), target = 'girl', type = IT_Accessory, pic = 'Cat ears.webp', rank = 1, rarity = 4, price = 2500, effects = (Effect('change', 'service results', 1), ), ),
                    Item(name = _('Nurse hat'), target = 'girl', type = IT_Accessory, pic = 'Nurse hat.webp', rank = 1, rarity = 4, price = 2500, effects = (Effect('change', 'sex results', 1), ), ),
                    Item(name = _('Leather cap'), target = 'girl', type = IT_Accessory, pic = 'Leather cap.webp', rank = 1, rarity = 4, price = 2500, effects = (Effect('change', 'anal results', 1), ), ),
                    Item(name = _('Maid hat'), target = 'girl', type = IT_Accessory, pic = 'Maid hat.webp', rank = 1, rarity = 4, price = 2500, effects = (Effect('change', 'fetish results', 1), ), ),
                    Item(name = _('Magic notebook'), target = 'MC', type = IT_Passive, pic = 'Magic notebook.webp', template = False, rank = 1, rarity = "S", price = 0, effects = (Effect('special', 'notebook', 1), ), description =__("This handy notebook will store all the information you know about your girls. It magically records all your thoughts. Wait, don't think about {i}that{/i}... Too late."), hidden_effect = True),
                    Item(name = _('Healing powder'), target = 'minion', type = IT_Misc, pic = 'healing powder.webp', template = False, rank = 1, rarity = "M", charges = 1, price = 100, effects = (Effect('special', 'heal minion', 1), ), description =__("This mysterious powder from the East will heal a minion's wounds or repair a magical artefact. Side effects may include dizziness, horniness, tentacles sprouting all over body.")),
                    Item(name = _('Cimerian scrap'), target = 'misc', type = IT_Misc, pic = 'Cimerian scrap.webp', sound=s_vibro, template = False, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 250, effects = (), description =__("A mysterious piece of ancient technological junk.")),
                    Item(name = _('Cimerian artefact'), target = 'misc', type = IT_Misc, pic = 'Cimerian artefact.webp', sound=s_vibro, template = False, rank = 1, max_rank = 5, rarity = 4, charges = 1, price = 1000, effects = (), description =__("A mysterious piece of ancient machinery. Also, junk.")),
                    Item(name = _("Lightning Rod"), target = 'MC', type = IT_Story, pic = "lightning rod.webp", template=False, rank=2, max_rank = 5, rarity=3, price = 1000, effects = (), description =__("Prevents lightning bolts from hurting you. It could save your ass in the right situation, although the chance to be hit by lightning while working in a brothel is very low. A syphilis rod might be more useful.")),

                    Item(name = _('White flower'), target = 'girl', type = IT_Flower, pic = 'White flower.webp', template = False, rank = 1, max_rank = 5, rarity = "F", price = 75, effects = (Effect('flower', 'white', 1), ), description ="白百合花象征着纯洁的爱情，别用你肮脏的思想玷污它！", hidden_effect = True),
                    Item(name = _('Yellow flower'), target = 'girl', type = IT_Flower, pic = 'Yellow flower.webp', template = False, rank = 1, max_rank = 5, rarity = "F", price = 75, effects = (Effect('flower', 'yellow', 1), ), description ="康乃馨能够驱逐病痛和悲伤，用它来抚慰少女受伤的心灵吧！", hidden_effect = True),
                    Item(name = _('Red flower'), target = 'girl', type = IT_Flower, pic = 'Red flower.webp', template = False, rank = 1, max_rank = 5, rarity = "F", price = 75, effects = (Effect('flower', 'red', 1), ), description ="玫瑰花可以用来泡浴，酿酒，香薰....难道你要用它表白？", hidden_effect = True),
                    Item(name = _('Green flower'), target = 'girl', type = IT_Flower, pic = 'Green flower.webp', template = False, rank = 1, max_rank = 5, rarity = "F", price = 75, effects = (Effect('flower', 'green', 1), ), description ="小小的绣球花可以戴在女孩的发髻旁，别有韵味。", hidden_effect = True),
                    Item(name = _('Blue flower'), target = 'girl', type = IT_Flower, pic = 'Blue flower.webp', template = False, rank = 1, max_rank = 5, rarity = "F", price = 75, effects = (Effect('flower', 'blue', 1), ), description ="矢车菊被风吹起时，就像自由的小鸟，自由是无价之宝。", hidden_effect = True),
                    Item(name = _('Orange flower'), target = 'girl', type = IT_Flower, pic = 'Orange flower.webp', template = False, rank = 1, max_rank = 5, rarity = "F", price = 75, effects = (Effect('flower', 'orange', 1), ), description ="郁金香被大面积地种植于农田中，微风轻拂~香飘十里。", hidden_effect = True),
                    Item(name = _('Purple flower'), target = 'girl', type = IT_Flower, pic = 'Purple flower.webp', template = False, rank = 1, max_rank = 5, rarity = "F", price = 75, effects = (Effect('flower', 'purple', 1), ), description ="紫罗兰代表了约定与等待，你是个守约的人吗？", hidden_effect = True),
                    Item(name = _('Pink flower'), target = 'girl', type = IT_Flower, pic = 'Pink flower.webp', template = False, rank = 1, max_rank = 5, rarity = "F", price = 75, effects = (Effect('flower', 'pink', 1), ), description ="芙蓉很适合那些含苞待放的少女们，爱恋之心逐渐生根发芽。", hidden_effect = True),
                    Item(name = _('Black flower'), target = 'girl', type = IT_Flower, pic = 'Black flower.webp', template = False, rank = 1, max_rank = 5, rarity = "F", price = 75, effects = (Effect('flower', 'black', 1), ), description ="曼陀罗象征着女性的自主与独立，她们勇敢、坚强。", hidden_effect = True),
                    ]


        # SPECIAL ITEMS AND FURNITURE #

        vitals_scanner = Furniture(_('Strange machine'), type='Gizmos', pic='scanner.webp', rank=2, chapter=2, cost=[('wood', 20), ('dye', 20), ('leather', 20)], duration=4, effects=[Effect("special", "autorest", 1, scope="brothel")], base_description="这个神秘的机器散发着一股奥术能量的波动。") #  It scans your girls automatically to make sure they are fit to work.

        billboard = Furniture(_('Clockwork billboard'), type='Furnishing', pic='billboard.webp', rank=2, chapter=2, cost=[('wood', 40), ('dye', 25), ('leather', 10)], duration=5, effects=[Effect("special", "advanced advertising", 1, scope="brothel")], base_description="这个华丽的广告牌能吸引许多人的注意。可以解锁高级广告设置。") #  Unlocks advanced advertising settings

        extractor_items = {"extractor1" : Item(name="Extractor Mk I", target="MC", type=IT_Story, pic="extractor1.webp", template = False, rarity = "S", price = 5000, effects=[], description =__("This strange steam machine lets you harvest wood, dye or leather automatically. Deploy on site.")),
                            "extractor2" : Item(name="Extractor Mk II", target="MC", type=IT_Story, pic="extractor2.webp", template = False, rarity = "S", price = 25000, effects=[], description =__("This strange steam machine lets you harvest marble, silk or ore automatically. Deploy on site.")),
                            }

        mizuki_kimono = Item(name = _("Mizuki's Kimono"), target = 'MC', type = IT_Story, pic = 'Kimono.webp', template = False, rank = 1, rarity = "S", price = 0, pic_dir="dress", description =__("A kimono left behind by Mizuki Ike, the mysterious eldest Kunoichi."), hidden_effect = True).get_instance()

        subaru_tunic = Item(name = _("Subaru's Tunic"), target = 'girl', type = IT_Dress, pic = 'subaru tunic.webp', template = False, rank = 1, rarity = "S", price = 1000, effects = [Effect("special", "ignore energy", 1, chance=0.25)], description =__("Once worn by a fearsome kunoichi, this sturdy tunic is no longer of use to her."))

        makibishi = Item(name = _("Makibishi"), target = 'MC', type = IT_Misc, pic = 'bronze makibishi.webp', template = False, rank = 1, rarity = "S", price = 500, description =__("Automatically catches a Kunoichi when hunting ninjas (skip minigame)."), hidden_effect = True)
#                       Item(name = _("Iron Makibishi"), target = 'MC', type = IT_Story, pic = 'iron makibishi.webp', template = False, rank = 2, rarity = "S", price = 1000, description =__("Slows down Kunoichi movements during ninja hunt (medium effect)."), hidden_effect = True),
#                       Item(name = _("Steel Makibishi"), target = 'MC', type = IT_Story, pic = 'steel makibishi.webp', template = False, rank = 3, rarity = "S", price = 1500, description =__("Slows down Kunoichi movements during ninja hunt (large effect)."), hidden_effect = True),

        rep_item = Item(name = _("Royal Commendation"), target = "girl", type = IT_Misc, pic = 'edict.webp', template = False, rank = 1, rarity = "S", price = 1000, effects = [Effect("gain", "reputation", 10)], description =__("This honorific scroll bears the seal of the Pharo royal family. Proudly displayed in a girl's room, it is sure to get people's attention."))


        ## Already instantiated items (unique items, ready to add to MC inventory). This is important if direct inventory checks are done (item X in MC.items); Not recommended otherwise

        magic_notebook = Item(name = _('Magic notebook'), target = 'MC', type = IT_Passive, pic = 'Magic notebook.webp', template = False, rank = 1, rarity = "S", price = 0, effects = (Effect('special', 'notebook', 1), ), description =__("This handy notebook will store all the information you know about your girls. It magically writes down all your thoughts. Wait, don't think about {i}that{/i}... Too late."), hidden_effect = True).get_instance()

        toy_hammer = Item(name = _("Hammer Of Light"), target = 'MC', type = IT_Story, pic = 'toy hammer.webp', template = False, rank = 1, rarity = "S", price = 0, description =__("A diminutive 'warhammer' made of cheap materials. Supposed to work against the Kunoichi, but it looks like it couldn't even whack a mole."), hidden_effect = True).get_instance()

        mania_amulet = Item(name = _("Cheap charm"), target = 'MC', type = IT_Story, pic = 'cheap charm.webp', template = False, rank = 1, rarity = "S", price = 10, description =__("A cheap amulet found with a mysterious letter mentioning a club called 'Mania' in the guild quarter."), hidden_effect = True).get_instance()

        bast_letter = Item("Bast's love letter", "MC", type=IT_Story, pic="Scroll of etiquette.webp", template = False, rank = 1, rarity = "S", price = 0, effects = [], description =__("A love letter written by Bast to her former paramour. Contains incriminating information."), hidden_effect = True).get_instance()

        blueprint_item = Item(name = _('Ancient blueprint'), target = 'MC', type = IT_Story, pic = 'scanner blueprint.webp', template = False, rank = 1, rarity = "S", price = 0, effects = [], description =__("An ancient blueprint written on a light yet strong paper-like material. The instructions are foreign and indecipherable, but a skilled craftsman could perhaps make sense of it."), hidden_effect = True).get_instance()

        narika_hair = Item(name = _("Lock of Narika's hair"), target = 'MC', type = IT_Story, pic = 'hair.webp', template = False, rank = 1, rarity = "S", price = 0, description =__("A lock of pink hair, belonging to the Kunoichi prodigy Narika Shihoudou."), hidden_effect = True).get_instance()

        blue_ribbon = Item(name = _("Homura's ribbon"), target = 'MC', type = IT_Story, pic = 'blue ribbon.webp', template = False, rank = 1, rarity = "S", price = 0, pic_dir="necklace", description =__("A ribbon given to you by Lady Henso. Tie it to a pole in the city {b}Plaza{/b} to let her know you want to see her."), hidden_effect = True).get_instance()

        earth_rune = Item(name = _("Earth Rune"), target = 'MC', type = IT_Story, pic = 'earth rune.webp', template = False, rank = 1, rarity = "S", price = 0, pic_dir="misc", description =__("This runestone has a strong inhibitive effect on Earth magic and disorients their users. This could help you out against the Earth ninja."), hidden_effect = True).get_instance()
        water_rune = Item(name = _("Water Rune"), target = 'MC', type = IT_Story, pic = 'water rune.webp', template = False, rank = 1, rarity = "S", price = 0, pic_dir="misc", description =__("This runestone has a strong inhibitive effect on Water magic and disorients their users. This could help you out against the Water ninja."), hidden_effect = True).get_instance()
        void_rune = Item(name = _("Void Rune"), target = 'MC', type = IT_Story, pic = 'void rune.webp', template = False, rank = 1, rarity = "S", price = 0, pic_dir="misc", description =__("This runestone can manipulate time to slow down super fast people and objects, or something. This could help you out against the Void ninja."), hidden_effect = True).get_instance()
        fire_rune = Item(name = _("Fire Rune"), target = 'MC', type = IT_Story, pic = 'fire rune.webp', template = False, rank = 1, rarity = "S", price = 0, pic_dir="misc", description =__("This runestone has a strong inhibitive effect on Fire magic and disorients their users. You don't know any Fire magic users, so would that really be useful to you?"), hidden_effect = True).get_instance()

        MU_entry_scroll = Item(name = _("M.U. registration scroll"), target = 'MC', type = IT_Story, pic = 'Scroll of Gomorrah.webp', template = False, rank = 1, rarity = "S", price = 0, pic_dir="misc", description =__("This scroll gives you access to the Magic University for a week."), hidden_effect = True).get_instance()

        # Chaos

        chaos_full_charge = Item(name = _('Full Power Chaos'), target = 'MC', type = IT_Weapon, sellable=False, giveable=False, pic = 'Demon sword.webp', rank = 4, rarity = "S", price = 0, effects = (Effect('change', 'strength', 4), Effect('change', 'charisma', 4), Effect('change', 'spirit', 4)), description =__("The blade pulses with the dark fury of the greater daemon trapped inside. It refills its energy from cavorting with girls, somehow. It is fully charged.")).get_instance()
        chaos_high_charge = Item(name = _('Mid Power Chaos'), target = 'MC', type = IT_Weapon, sellable=False, giveable=False, pic = 'Demon sword.webp', rank = 4, rarity = "S", price = 0, effects = (Effect('change', 'strength', 3), Effect('change', 'charisma', 3), Effect('change', 'spirit', 3)), description =__("The blade pulses with the dark fury of the greater daemon trapped inside. It refills its energy from cavorting with girls, somehow. It is well charged.")).get_instance()
        chaos_low_charge = Item(name = _('Low Power Chaos'), target = 'MC', type = IT_Weapon, sellable=False, giveable=False, pic = 'Demon sword.webp', rank = 4, rarity = "S", price = 0, effects = (Effect('change', 'strength', 2), Effect('change', 'charisma', 2), Effect('change', 'spirit', 2)), description =__("The blade pulses with the dark fury of the greater daemon trapped inside. It refills its energy from cavorting with girls, somehow. It is partially charged.")).get_instance()
        chaos_no_charge = Item(name = _('Depleted Chaos'), target = 'MC', type = IT_Weapon, sellable=False, giveable=False, pic = 'Demon sword.webp', rank = 4, rarity = "S", price = 0, effects = (Effect('change', 'strength', 1), Effect('change', 'charisma', 1), Effect('change', 'spirit', 1)), description =__("The blade pulses with the dark fury of the greater daemon trapped inside. It refills its energy from cavorting with girls, somehow. It is not charged.")).get_instance()

        # NG+ items (do not instantiate)

        seduction_potion = Item(name = _("Potion of Seduction"), target = 'gift', type = IT_Gift, pic = 'love potion.webp', template = False, rank = 1, rarity = "S", price = 0, effects = [Effect("potion", "seduction", 1)], pic_dir="misc", description =__("This potion raises the relationship level with any free girl in the city to the next step."), sound = s_bubbling, hidden_effect = True)
        restoration_balm = Item(name = _("Balm of Restoration"), target = 'girl', type = IT_Misc, pic = 'monster juice.webp', template = False, rank = 1, rarity = "S", price = 0, effects = [Effect("special", "virginity", 1)], pic_dir="misc", description =__("This balm is prized by the nobility. It restores a girl's virginity (in appearance, anyway)."), sound = s_dress, hidden_effect = True)
        bliss_incense = Item(name = _("Incense of Bliss"), target = 'girl', type = IT_Misc, pic = 'extractor2.webp', template = False, rank = 1, rarity = "S", price = 0, effects = [Effect("special", "sanity", 1)], pic_dir="misc", description =__("This exotic drug helps forget even the worst traumas."), sound = s_fire, hidden_effect = True)
        magic_powder = Item(name = _("Magic Powder"), target = 'MC', type = IT_Misc, pic = 'healing powder.webp', template = False, rank = 1, rarity = "S", price = 0, effects = [Effect("special", "MC interactions", 1)], pic_dir="misc", description =__("Snort some to recover all of your AP and Mana. It's completely legal. Maybe."), sound = s_maniacal_laugh, hidden_effect = True)
        wyvern_egg = Item(name = _('Wyvern egg'), target = 'girl', type = IT_Misc, pic = 'Wyvern egg.webp', template = False, rank = 1, rarity = "S", charges = 1, price = 10000, sellable=False, effects = (Effect('gain', 'perk', 1), ), description =__("A dish fit for a brothel queen."), sound = s_roar) # Also used in events/gift shop


    ### TEMPLATE ITEMS ###

        template_items = [
                            Item(name = _('Stolen underwear'), target = 'MC', type = IT_Misc, pic = 'Stolen underwear.webp', template = True, rank = 1, max_rank = 5, rarity = "S", charges = 1, price = 500, effects = (Effect('gain', 'prestige', 2), ), description =__("So you're into these, eh?")),
                            Item(name = _('Romantic novel'), target = 'gift', type = IT_Gift, pic = 'Romantic novel.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 100, effects = (Effect('gift', 'cute', 1), Effect('gift', 'book', 1), ), description =__(  "A knight in shining armor. A princess. A plumber. The usual."), hidden_effect = True),
                            Item(name = _('Erotic manual'), target = 'gift', type = IT_Gift, pic = 'Erotic manual.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 100, effects = (Effect('gift', 'erotica', 1), Effect('gift', 'book', 1), ), description =__(  "50 positions that you can only achieve using black magic."), hidden_effect = True),
                            Item(name = _('Goldleaf book'), target = 'gift', type = IT_Gift, pic = 'Goldleaf book.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 100, effects = (Effect('gift', 'precious', 1), Effect('gift', 'book', 1), ), description =__(  "What does it talk about? Who cares! It's shiny."), hidden_effect = True),
                            Item(name = _('Book of magical cocktails'), target = 'gift', type = IT_Gift, pic = 'Book of magical cocktails.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 100, effects = (Effect('gift', 'drinks', 1), Effect('gift', 'book', 1), ), description =__(  "Warning: consuming those potions may result in loss of memory. Also,  dignity."), hidden_effect = True),
                            Item(name = _('Pet'), target = 'gift', type = IT_Gift, pic = 'Pet.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 100, effects = (Effect('gift', 'cute', 1), Effect('gift', 'precious', 1), ), description =__(  "Isn't he adorable? As long as he doesn't bite your hand off..."), hidden_effect = True),
                            Item(name = _('Silky nighties'), target = 'gift', type = IT_Gift, pic = 'Silky nighties.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 100, effects = (Effect('gift', 'cute', 1), Effect('gift', 'erotica', 1), ), description =__(  "Smooth and sexy."), hidden_effect = True),
                            Item(name = _('Sakura liquor'), target = 'gift', type = IT_Gift, pic = 'Sakura liquor.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 100, effects = (Effect('gift', 'cute', 1), Effect('gift', 'drinks', 1), ), description =__(  "A subtle drink made of distilled flower petals."), hidden_effect = True),
                            Item(name = _('Sexy high heels'), target = 'gift', type = IT_Gift, pic = 'Sexy high heels.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 100, effects = (Effect('gift', 'erotica', 1), Effect('gift', 'precious', 1), ), description =__(  "Some women would kill to get their hands on those shoes. Actually,  they're a little blood spattered."), hidden_effect = True),
                            Item(name = _('Champagne'), target = 'gift', type = IT_Gift, pic = 'Champagne.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 100, effects = (Effect('gift', 'drinks', 1), Effect('gift', 'precious', 1), ), description =__(  "'Le Nouveau Riche': A strong drink; also, a statement that you can afford it."), hidden_effect = True),
                            Item(name = _('Aphrodisiac'), target = 'gift', type = IT_Gift, pic = 'Aphrodisiac.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 100, effects = (Effect('gift', 'drinks', 1), Effect('gift', 'erotica', 1), ), description =__(  "Fire in your belly,  fire in your pants..."), hidden_effect = True),
                            Item(name = _('Pretty ring'), target = 'girl', type = IT_Ring, pic = 'Pretty ring.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 150, effects = (Effect('change', 'beauty', 5), ), ),
                            Item(name = _('Bronze ring'), target = 'girl', type = IT_Ring, pic = 'Bronze ring.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 150, effects = (Effect('change', 'body', 5), ), ),
                            Item(name = _('Zanic ring'), target = 'girl', type = IT_Ring, pic = 'Zanic ring.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 150, effects = (Effect('change', 'charm', 5), ), ),
                            Item(name = _('Silver ring'), target = 'girl', type = IT_Ring, pic = 'Silver ring.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 150, effects = (Effect('change', 'refinement', 5), ), ),
                            Item(name = _('Gold ring'), target = 'girl', type = IT_Ring, pic = 'Gold ring.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 250, effects = (Effect('change', 'libido', 5), ), ),
                            Item(name = _('Marine ring'), target = 'girl', type = IT_Ring, pic = 'Marine ring.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 250, effects = (Effect('change', 'sensitivity', 5), ), ),
                            Item(name = _('Iron ring'), target = 'girl', type = IT_Ring, pic = 'Iron ring.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 375, effects = (Effect('change', 'obedience', 5), ), ),
                            Item(name = _('Wooden ring'), target = 'girl', type = IT_Ring, pic = 'Wooden ring.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 250, effects = (Effect('change', 'constitution', 5), ), ),
                            Item(name = _('Blue ribbon'), target = 'girl', type = IT_Necklace, pic = 'Blue ribbon.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 100, effects = (Effect('boost', 'beauty gains', 0.1), ), ),
                            Item(name = _('Pearl necklace'), target = 'girl', type = IT_Necklace, pic = 'Pearl necklace.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 100, effects = (Effect('boost', 'body gains', 0.1), ), ),
                            Item(name = _('Moon necklace'), target = 'girl', type = IT_Necklace, pic = 'Moon necklace.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 100, effects = (Effect('boost', 'charm gains', 0.1), ), ),
                            Item(name = _('Ivory necklace'), target = 'girl', type = IT_Necklace, pic = 'Ivory necklace.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 100, effects = (Effect('boost', 'refinement gains', 0.1), ), ),
                            Item(name = _('Choker necklace'), target = 'girl', type = IT_Necklace, pic = 'Choker necklace.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 250, effects = (Effect('boost', 'libido gains', 0.1), ), ),
                            Item(name = _('Dog collar'), target = 'girl', type = IT_Necklace, pic = 'Dog collar.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 250, effects = (Effect('boost', 'obedience gains', 0.1), ), ),
                            Item(name = _('Silver chain'), target = 'girl', type = IT_Necklace, pic = 'Silver chain.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 250, effects = (Effect('boost', 'sensitivity gains', 0.1), ), ),
                            Item(name = _('Dagger necklace'), target = 'girl', type = IT_Necklace, pic = 'Dagger necklace.webp', template = True, rank = 1, max_rank = 5, rarity = 2, price = 250, effects = (Effect('boost', 'constitution gains', 0.1), ), ),
                            Item(name = _('Gold bag'), target = 'girl', type = IT_Misc, pic = 'Gold bag.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 600, effects = (Effect('special', 'level', 5), ), description =__(  "Instant level up. Use it wisely..."), adjectives = "ring"),
                            Item(name = _('Jewel bag'), target = 'girl', type = IT_Misc, pic = 'Jewel bag.webp', template = True, rank = 1, max_rank = 5, rarity = 3, charges = 1, price = 500, effects = (Effect('gain', 'skill points', 5), ), description =__(  "Get extra skill points.")),
                            Item(name = _('Knowledge scroll'), target = 'girl', type = IT_Misc, pic = 'Knowledge scroll.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 400, effects = (Effect('gain', 'xp', 50), ), description =__(  "Get free xp."), adjectives = "scroll"),
                            Item(name = _('Medicine bag'), target = 'girl', type = IT_Misc, pic = 'Medicine bag.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 250, effects = (Effect('instant', 'heal', 2), ), description =__(  "")),
                            Item(name = _('Tonic'), target = 'girl', type = IT_Misc, pic = 'Tonic.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 75, effects = (Effect('gain', 'energy', 20), ), description =__(  "")),
                            Item(name = _('Wine'), target = 'girl', type = IT_Misc, pic = 'Wine.webp', template = True, rank = 1, max_rank = 5, rarity = 1, charges = 1, price = 75, effects = (Effect('gain', 'mood', 10), ), description =__(  "")),
                            Item(name = _('Apple'), target = 'girl', type = IT_Food, pic = 'Apple.webp', template = True, rank = 1, max_rank = 6, rarity = 1, charges = 1, price = 50, effects = (Effect('change', 'beauty', 5, duration=10), Effect('instant', 'heal', 1, 0.5)), description =__(  "An apple a day keeps the doctor away.")),
                            Item(name = _('Pear'), target = 'girl', type = IT_Food, pic = 'Pear.webp', template = True, rank = 1, max_rank = 6, rarity = 1, charges = 1, price = 50, effects = (Effect('change', 'body', 5, duration=10), Effect('instant', 'heal', 1, 0.5)), ),
                            Item(name = _('Peach'), target = 'girl', type = IT_Food, pic = 'Peach.webp', template = True, rank = 1, max_rank = 6, rarity = 1, charges = 1, price = 50, effects = (Effect('change', 'charm', 5, duration=10), Effect('instant', 'heal', 1, 0.5)), ),
                            Item(name = _('Grapes'), target = 'girl', type = IT_Food, pic = 'Grapes.webp', template = True, rank = 1, max_rank = 6, rarity = 1, charges = 1, price = 50, effects = (Effect('change', 'refinement', 5, duration=10), Effect('instant', 'heal', 1, 0.5)), ),
                            Item(name = _('Sausage'), target = 'girl', type = IT_Food, pic = 'Sausage.webp', template = True, rank = 1, max_rank = 6, rarity = 1, charges = 1, price = 75, effects = (Effect('change', 'libido', 5, duration=10), Effect('instant', 'heal', 1, 0.5)), ),
                            Item(name = _('Cheese'), target = 'girl', type = IT_Food, pic = 'Cheese.webp', template = True, rank = 1, max_rank = 6, rarity = 1, charges = 1, price = 75, effects = (Effect('change', 'sensitivity', 5, duration=10), Effect('instant', 'heal', 1, 0.5)), ),
                            Item(name = _('Chicken'), target = 'girl', type = IT_Food, pic = 'Chicken.webp', template = True, rank = 1, max_rank = 6, rarity = 1, charges = 1, price = 90, effects = (Effect('change', 'obedience', 5, duration=10), Effect('instant', 'heal', 1, 0.5)), ),
                            Item(name = _('Roastbeef'), target = 'girl', type = IT_Food, pic = 'Roastbeef.webp', template = True, rank = 1, max_rank = 6, rarity = 1, charges = 1, price = 75, effects = (Effect('change', 'constitution', 5, duration=10), Effect('instant', 'heal', 1, 0.5)), ),
                            Item(name = _('Love potion'), target = 'girl', type = IT_Misc, pic = 'Love potion.webp', template = True, rank = 1, max_rank = 6, rarity = 2, charges = 1, price = 100, effects = (Effect('gain', 'love', 2.5), ), description =__("Who said money can't buy you love?")),
                            Item(name = _('Monster juice'), target = 'girl', type = IT_Misc, pic = 'Monster juice.webp', template = True, rank = 1, max_rank = 6, rarity = 2, charges = 1, price = 60, effects = (Effect('gain', 'fear', 2.5), ), description =__("You don't want to know from which monster body parts this came from.")),
                            Item(name = _('Pink panties'), target = 'girl', type = IT_Accessory, pic = 'Pink panties.webp', template = True, rank = 1, max_rank = 6, rarity = 1, price = 125, effects = (Effect('change', 'beauty', 5), ), ),
                            Item(name = _('Hot pants'), target = 'girl', type = IT_Accessory, pic = 'Hot pants.webp', template = True, rank = 1, max_rank = 6, rarity = 1, price = 125, effects = (Effect('change', 'body', 5), ), ),
                            Item(name = _('Lowcut panties'), target = 'girl', type = IT_Accessory, pic = 'Lowcut panties.webp', template = True, rank = 1, max_rank = 6, rarity = 1, price = 125, effects = (Effect('change', 'charm', 5), ), ),
                            Item(name = _('Lace panties'), target = 'girl', type = IT_Accessory, pic = 'Lace panties.webp', template = True, rank = 1, max_rank = 6, rarity = 1, price = 125, effects = (Effect('change', 'refinement', 5), ), ),
                            Item(name = _('Sexy panties'), target = 'girl', type = IT_Accessory, pic = 'Sexy panties.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 250, effects = (Effect('change', 'libido', 5), ), ),
                            Item(name = _('Seethrough panties'), target = 'girl', type = IT_Accessory, pic = 'Seethrough panties.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 250, effects = (Effect('change', 'sensitivity', 5), ), ),
                            Item(name = _('Chastity belt'), target = 'girl', type = IT_Accessory, pic = 'Chastity belt.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 350, effects = (Effect('change', 'obedience', 5), ), ),
                            Item(name = _('Thong'), target = 'girl', type = IT_Accessory, pic = 'Thong.webp', template = True, rank = 1, max_rank = 6, rarity = 2, price = 175, effects = (Effect('change', 'constitution', 5), ), ),
                            
                            
                            Item(name = _('Emerald ring'), target = 'girl', type = IT_Ring, pic = 'Emerald ring.webp', template = True, rank = 1, max_rank = 5, rarity = 3, price = 500, effects = (Effect('change', 'service', 5), ), ),
                            Item(name = _('Ruby ring'), target = 'girl', type = IT_Ring, pic = 'Ruby ring.webp', template = True, rank = 1, max_rank = 5, rarity = 3, price = 500, effects = (Effect('change', 'sex', 5), ), ),
                            Item(name = _('Amber ring'), target = 'girl', type = IT_Ring, pic = 'Amber ring.webp', template = True, rank = 1, max_rank = 5, rarity = 3, price = 500, effects = (Effect('change', 'anal', 5), ), ),
                            Item(name = _('Sapphire ring'), target = 'girl', type = IT_Ring, pic = 'sapphire ring.webp', template = True, rank = 1, max_rank = 5, rarity = 3, price = 500, effects = (Effect('change', 'fetish', 5), ), ),
                            Item(name = _('Scroll of bartending'), target = 'girl', type = IT_Misc, pic = 'Scroll of bartending.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 150, effects = (Effect('gain', 'waitress jp', 10), ), adjectives = "scroll"),
                            Item(name = _('Scroll of whirling'), target = 'girl', type = IT_Misc, pic = 'Scroll of whirling.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 150, effects = (Effect('gain', 'dancer jp', 10), ), adjectives = "scroll"),
                            Item(name = _('Scroll of rubbing'), target = 'girl', type = IT_Misc, pic = 'Scroll of rubbing.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 150, effects = (Effect('gain', 'masseuse jp', 10), ), adjectives = "scroll"),
                            Item(name = _('Scroll of etiquette'), target = 'girl', type = IT_Misc, pic = 'Scroll of etiquette.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 150, effects = (Effect('gain', 'geisha jp', 10), ), adjectives = "scroll"),
                            Item(name = _('Scroll of Onan'), target = 'girl', type = IT_Misc, pic = 'Scroll of Onan.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 150, effects = (Effect('gain', 'service jp', 10), ), adjectives = "scroll"),
                            Item(name = _('Scroll of Eros'), target = 'girl', type = IT_Misc, pic = 'Scroll of Eros.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 150, effects = (Effect('gain', 'sex jp', 10), ), adjectives = "scroll"),
                            Item(name = _('Scroll of Sodom'), target = 'girl', type = IT_Misc, pic = 'Scroll of Sodom.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 150, effects = (Effect('gain', 'anal jp', 10), ), adjectives = "scroll"),
                            Item(name = _('Scroll of Gomorrah'), target = 'girl', type = IT_Misc, pic = 'Scroll of Gomorrah.webp', template = True, rank = 1, max_rank = 5, rarity = 2, charges = 1, price = 150, effects = (Effect('gain', 'fetish jp', 10), ), adjectives = "scroll"),
                            Item(name = _('Elvish-made penis enlarger'), target = 'minion', type = IT_Misc, pic = 'enlarger.webp', template = True, rank = 1, max_rank = 5, rarity = "M", charges = 1, price = 120, effects = (Effect('gain', 'stallion xp', 10), ), description =__("That's not mine. This sort of thing ain't my bag, baby!")),
                            Item(name = _('Machine lubricant'), target = 'minion', type = IT_Misc, pic = 'lubricant.webp', template = True, rank = 1, max_rank = 5, rarity = "M", charges = 1, price = 120, effects = (Effect('gain', 'machine xp', 10), ), description =__("Grease is good.")),
                            Item(name = _('Strange feed'), target = 'minion', type = IT_Misc, pic = 'feed.webp', template = True, rank = 1, max_rank = 5, rarity = "M", charges = 1, price = 120, effects = (Effect('gain', 'beast xp', 10), ), description =__("Like it when they hold onto your leg and rubs themselves up and down? Because this feed sure makes them wanna do that.")),
                            Item(name = _('Monster cookie'), target = 'minion', type = IT_Misc, pic = 'cookie.webp', template = True, rank = 1, max_rank = 5, rarity = "M", charges = 1, price = 120, effects = (Effect('gain', 'monster xp', 10), ), description =__("C is for cock-y."), adjectives = "food"),
                            
                            Item(name = '女仆装', target = 'girl', type = IT_Dress, pic=random.choice([ '女仆装.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 500 effects = (Effect('change', 'beauty', 5), ), description = "女仆工作时穿的制服，里面通常都不穿内衣，不信你掀开裙子看看"),
                            Item(name = '兔女郎', target = 'girl', type = IT_Dress, pic=random.choice([ '兔女郎.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 500 effects = (Effect('change', 'charm', 5), ), description = "耳朵，尾巴，渔网袜。记得给她最爱吃的大萝卜。"),
                            Item(name = '浴衣', target = 'girl', type = IT_Dress, pic=random.choice([ '浴衣.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 500 effects = (Effect('change', 'body', 5), ), description = "担心被水弄湿？那就穿上它为客人提供服务吧！"),
                            Item(name = '舞女装', target = 'girl', type = IT_Dress, pic=random.choice([ '舞女装.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 500 effects = (Effect('change', 'refinement', 5), ), description = "伴随着舞蹈，身上的布料有时候会越来越少。"),
                            
                            Item(name = '吊带裙', target = 'girl', type = IT_Dress, pic=random.choice([ '吊带裙.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 650 effects = (Effect('change', 'libido', 5), ), description = "你听说过一个词叫做老肩巨滑吗？"),
                            Item(name = '广袖裙', target = 'girl', type = IT_Dress, pic=random.choice([ '广袖裙.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 650 effects = (Effect('change', 'sensitivity', 5), ), description = "袖里藏着乾坤，舞动起来如同流彩一般。"),
                            Item(name = '裹身裙', target = 'girl', type = IT_Dress, pic=random.choice([ '裹身裙.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 650 effects = (Effect('change', 'constitution', 5), ), description = "完美地包裹住了胸，腰，臀，将身材曲线展现的淋漓尽致。"),
                            Item(name = '大衣', target = 'girl', type = IT_Dress, pic=random.choice([ '大衣.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 650 effects = (Effect('change', 'obedience', 5), ), description = "宽松的大衣，里面藏着什么呢？"),
                            
                            Item(name = '浴巾', target = 'girl', type = IT_Dress, pic=random.choice([ '浴巾.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 800 effects = (Effect('change', 'service', 5), ), description = "美人出浴，最是迷人，记得擦干水渍不然容易着凉。"),
                            Item(name = '丝袜', target = 'girl', type = IT_Dress, pic=random.choice([ '丝袜.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 800 effects = (Effect('change', 'sex', 5), ), description = "不管黑丝白丝，能穿就是好丝。"),
                            Item(name = '一线天', target = 'girl', type = IT_Dress, pic=random.choice([ '一线天.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 800 effects = (Effect('change', 'anal', 5), ), description = "没有两侧的束缚，仅留下一缕布料挡在中央。"),
                            Item(name = '绑带', target = 'girl', type = IT_Dress, pic=random.choice([ '绑带.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 800 effects = (Effect('change', 'fetish', 5), ), description = "被邪恶的绷带束缚住的宝藏，等待着勇者将其解放。"),
                            
                            Item(name = '汉服', target = 'girl', type = IT_Dress, pic=random.choice([ '汉服.webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1000 effects = (Effect('change', 'charm', 5), Effect('change', 'beauty', 5), ), description = "传统而又古典的服饰，显露出一股儒雅气息。"),
                            Item(name = '洋装', target = 'girl', type = IT_Dress, pic=random.choice([ '洋装.webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1000 effects = (Effect('change', 'beauty', 5), Effect('change', 'body', 5), ), description = "女孩喜欢的时尚潮流穿搭。"),
                            Item(name = '衬衫', target = 'girl', type = IT_Dress, pic=random.choice([ '衬衫.webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1000 effects = (Effect('change', 'beauty', 5), Effect('change', 'refinement', 5), ), description = "衬衫就得不合身的才好，不管大了还是小了。"),
                            Item(name = '旗袍', target = 'girl', type = IT_Dress, pic=random.choice([ '旗袍.webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1000 effects = (Effect('change', 'charm', 5), Effect('change', 'body', 5), ), description = "传统的东方服饰，侧边开衩的设计令人眼前一亮。"),
                            Item(name = '婚纱', target = 'girl', type = IT_Dress, pic=random.choice([ '婚纱.webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1000 effects = (Effect('change', 'charm', 5), Effect('change', 'refinement', 5), ), description = "红色象征着喜悦，白色象征着纯洁，不过反正入了洞房都要脱掉的。"),
                            Item(name = '晚礼服', target = 'girl', type = IT_Dress, pic=random.choice([ '晚礼服.webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1000 effects = (Effect('change', 'body', 5), Effect('change', 'refinement', 5), ), description = "穿上它进入宴席，你将成为全场的焦点。"),
                            
                            Item(name = '肚兜', target = 'girl', type = IT_Dress, pic=random.choice([ '肚兜.webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1200 effects = (Effect('change', 'libido', 5), Effect('change', 'sensitivity', 5), ), description = "传统的内衣，面料做工精细。"),
                            Item(name = '牛仔裤', target = 'girl', type = IT_Dress, pic=random.choice([ '牛仔裤.webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1200 effects = (Effect('change', 'libido', 5), Effect('change', 'constitution', 5), ), description = "有多少女性为了穿上它而付出惨痛的代价？"),
                            Item(name = '口罩', target = 'girl', type = IT_Dress, pic=random.choice([ '口罩.webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1200 effects = (Effect('change', 'libido', 5), Effect('change', 'obedience', 5), ), description = "口罩不戴在嘴巴上还能戴在哪里？你瞧。"),
                            Item(name = '蕾丝内衣', target = 'girl', type = IT_Dress, pic=random.choice([ '蕾丝内衣.webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1200 effects = (Effect('change', 'constitution', 5), Effect('change', 'sensitivity', 5), ), description = "性感而又不落俗套，纵享丝滑。"),
                            Item(name = '蕾丝内裤', target = 'girl', type = IT_Dress, pic=random.choice([ '蕾丝内裤.webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1200 effects = (Effect('change', 'obedience', 5), Effect('change', 'sensitivity', 5), ), description = "性感而又不落俗套，纵享丝滑。"),
                            Item(name = '针织衣', target = 'girl', type = IT_Dress, pic=random.choice([ '针织衣.webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1200 effects = (Effect('change', 'constitution', 5), Effect('change', 'obedience', 5), ), description = "小心激烈运动时摩擦产生的静电，噼啪~"),
                            
                            Item(name = '绒制内衣', target = 'girl', type = IT_Dress, pic=random.choice([ '绒制内衣.webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1500 effects = (Effect('change', 'service', 5), Effect('change', 'sex', 5), ), description = "软乎乎的，暖洋洋的，还有一点痒。"),
                            Item(name = '亮片内衣', target = 'girl', type = IT_Dress, pic=random.choice([ '亮片内衣.webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1500 effects = (Effect('change', 'service', 5), Effect('change', 'anal', 5), ), description = "闪亮的金属片令人眼花缭乱，白花花的肉体令人目不暇接。"),
                            Item(name = '睡衣', target = 'girl', type = IT_Dress, pic=random.choice([ '睡衣.webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1500 effects = (Effect('change', 'service', 5), Effect('change', 'fetish', 5), ), description = "既然要追求刺激，那就坚持到底咯~"),
                            Item(name = '塑形内衣', target = 'girl', type = IT_Dress, pic=random.choice([ '塑形内衣.webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1500 effects = (Effect('change', 'sex', 5), Effect('change', 'anal', 5), ), description = "束腰，挺胸，让你尽显女性风采。"),
                            Item(name = '渔网内衣', target = 'girl', type = IT_Dress, pic=random.choice([ '渔网内衣.webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1500 effects = (Effect('change', 'sex', 5), Effect('change', 'fetish', 5), ), description = "它的质量好到可以用来捕鱼。"),
                            Item(name = '超短裙', target = 'girl', type = IT_Dress, pic=random.choice([ '超短裙.webp']), template = True, rank = 2, max_rank = 6, rarity = 2, price = 1500 effects = (Effect('change', 'fetish', 5), Effect('change', 'anal', 5), ), description = "只要稍微动起来就会露出底下的神秘地带，你都保护了些什么啊。"),
                            
                            Item(name = '短胸衣', target = 'girl', type = IT_Dress, pic=random.choice([ '短胸衣.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 1200 effects = (Effect('change', 'beauty', 5), Effect('change', 'charm', 5), Effect('change', 'refinement', -5), Effect('change', 'body', 5), , ), description = "月有阴晴圆缺，露出的一半引人遐思。"),
                            Item(name = '开胸装', target = 'girl', type = IT_Dress, pic=random.choice([ '开胸装.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 1200 effects = (Effect('change', 'beauty', 5), Effect('change', 'charm', 5), Effect('change', 'refinement', 5), Effect('change', 'body', -5), , ), description = "哺乳期妈妈的衣服，什么？你说你也是要喝奶的大宝宝？"),
                            Item(name = '镂空装', target = 'girl', type = IT_Dress, pic=random.choice([ '镂空装.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 1200 effects = (Effect('change', 'beauty', -5), Effect('change', 'charm', 5), Effect('change', 'refinement', 5), Effect('change', 'body', 5), , ), description = "方便透气的设计，也方便把手插进去。"),
                            Item(name = '露背装', target = 'girl', type = IT_Dress, pic=random.choice([ '露背装.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 1200 effects = (Effect('change', 'beauty', 5), Effect('change', 'charm', -5), Effect('change', 'refinement', 5), Effect('change', 'body', 5), , ), description = "多好的背啊，不拔个火罐可惜了。"),
                            Item(name = '露胸装', target = 'girl', type = IT_Dress, pic=random.choice([ '露胸装.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 1200 effects = (Effect('change', 'beauty', 5), Effect('change', 'charm', 5), Effect('change', 'refinement', 5), Effect('change', 'body', 5), , ), description = "深不见底的沟壑，值得亲自探索一下。"),
                            
                            Item(name = '学校泳装', target = 'girl', type = IT_Dress, pic=random.choice([ '学校泳装.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 1500 effects = (Effect('change', 'libido', -5), Effect('change', 'sensitivity', 5), Effect('change', 'obedience', 5), Effect('change', 'constitution', 5), ), description = "学校游泳课派发的统一款式，很老式但也很耐用。"),
                            Item(name = '竞技泳装', target = 'girl', type = IT_Dress, pic=random.choice([ '竞技泳装.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 1500 effects = (Effect('change', 'libido', 5), Effect('change', 'sensitivity', -5), Effect('change', 'obedience', 5), Effect('change', 'constitution', 5), ), description = "专为竞技而生，将水中的阻力减到最低。"),
                            Item(name = '高叉装', target = 'girl', type = IT_Dress, pic=random.choice([ '高叉装.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 1500 effects = (Effect('change', 'libido', 5), Effect('change', 'sensitivity', 5), Effect('change', 'obedience', 5), Effect('change', 'constitution', -5), ), description = "高叉设计能充分地展露身材，绷紧的布料能够凸显胸部。"),
                            Item(name = '比基尼', target = 'girl', type = IT_Dress, pic=random.choice([ '比基尼.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 1500 effects = (Effect('change', 'libido', 5), Effect('change', 'sensitivity', 5), Effect('change', 'obedience', -5), Effect('change', 'constitution', 5), ), description = "阳光，沙滩，当然少不了比基尼。"),
                            Item(name = '领带', target = 'girl', type = IT_Dress, pic=random.choice([ '领带.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 1500 effects = (Effect('change', 'libido', 5), Effect('change', 'sensitivity', 5), Effect('change', 'obedience', 5), Effect('change', 'constitution', 5), ), description = "领带在某种场合也是一种牵绳。"),
                            
                            Item(name = '开裆裤', target = 'girl', type = IT_Dress, pic=random.choice([ '开裆裤.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 1800 effects = (Effect('change', 'service', -5), Effect('change', 'sex', 5), Effect('change', 'anal', 5), Effect('change', 'fetish', 5), , ), description = "方便行事的设计，拉开拉链即可享用"),
                            Item(name = '裸体围裙', target = 'girl', type = IT_Dress, pic=random.choice([ '裸体围裙.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 1800 effects = (Effect('change', 'service', 5), Effect('change', 'sex', -5), Effect('change', 'anal', 5), Effect('change', 'fetish', 5), , ), description = "不要在她烹饪的时候从背后偷袭她，至少把火先关了。"),
                            Item(name = '轻纱', target = 'girl', type = IT_Dress, pic=random.choice([ '轻纱.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 1800 effects = (Effect('change', 'service', 5), Effect('change', 'sex', 5), Effect('change', 'anal', -5), Effect('change', 'fetish', 5), , ), description = "犹抱琵琶半遮面，令人忍不住想要一把扯下。"),
                            Item(name = '透视装', target = 'girl', type = IT_Dress, pic=random.choice([ '透视装.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 1800 effects = (Effect('change', 'service', 5), Effect('change', 'sex', 5), Effect('change', 'anal', 5), Effect('change', 'fetish', -5), , ), description = "特殊的面料可以伸缩自如，就像面团一样牵拉把玩。"),
                            Item(name = '调教服', target = 'girl', type = IT_Dress, pic=random.choice([ '调教服.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 1800 effects = (Effect('change', 'service', 5), Effect('change', 'sex', 5), Effect('change', 'anal', 5), Effect('change', 'fetish', 5), , ), description = "紧紧地捆绑勒出了丰满肉体的线条，对她为所欲为吧。"),
                            
                            Item(name = '护士制服', target = 'girl', type = IT_Dress, pic=random.choice([ '护士制服.webp']), template = True, rank = 1, max_rank = 6, rarity = 2, price = 1000 effects = (Effect('boost', 'beauty gains', 0.1), ), description = "来，把裤子脱掉，要给你打针了哦。"),
                            Item(name = '学生制服', target = 'girl', type = IT_Dress, pic=random.choice([ '学生制服.webp']), template = True, rank = 1, max_rank = 6, rarity = 2, price = 1000 effects = (Effect('boost', 'body gains', 0.1), ), description = "清纯的少女穿着清纯的制服，你是个好学生吗？"),
                            Item(name = '圣诞装', target = 'girl', type = IT_Dress, pic=random.choice([ '圣诞装.webp']), template = True, rank = 1, max_rank = 6, rarity = 2, price = 1000 effects = (Effect('boost', 'charm gains', 0.1), ), description = "圣诞快乐！你想要什么礼物？"),
                            Item(name = '空姐制服', target = 'girl', type = IT_Dress, pic=random.choice([ '空姐制服.webp']), template = True, rank = 1, max_rank = 6, rarity = 2, price = 1000 effects = (Effect('boost', 'refinement gains', 0.1), ), description = "看看你的力度能不能让她回忆起天空上的颠簸？"),
                            Item(name = '秘书装', target = 'girl', type = IT_Dress, pic=random.choice([ '秘书装.webp']), template = True, rank = 1, max_rank = 6, rarity = 2, price = 1200 effects = (Effect('boost', 'libido gains', 0.1), ), description = "有事秘书干，没事干秘书。"),
                            
                            Item(name = '教师制服', target = 'girl', type = IT_Dress, pic=random.choice([ '教师制服.webp']), template = True, rank = 1, max_rank = 6, rarity = 2, price = 1200 effects = (Effect('boost', 'obedience gains', 0.1), ), description = "你是生理课老是吗？让老师尝尝你的教鞭的威力吧！"),
                            Item(name = '修女服', target = 'girl', type = IT_Dress, pic=random.choice([ '修女服.webp']), template = True, rank = 1, max_rank = 6, rarity = 2, price = 1200 effects = (Effect('boost', 'sensitivity gains', 0.1), ), description = "修女，请用你的那里帮我驱逐身体里的恶魔。"),
                            Item(name = '女警制服', target = 'girl', type = IT_Dress, pic=random.choice([ '女警制服.webp']), template = True, rank = 1, max_rank = 6, rarity = 2, price = 1200 effects = (Effect('boost', 'constitution gains', 0.1), ), description = "是时候让让女警尝尝你的警棍的威力了！"),

                            Item(name = '乳铃', target = 'girl', type = IT_Dress, pic=random.choice([ '乳铃.webp']), template = True, rank = 2, max_rank = 6, rarity = 3, price = 1600 effects = (Effect('change', 'beauty', 6), Effect('change', 'charm', 6), Effect('change', 'refinement', 6), Effect('change', 'body', 6), Effect('change', 'defense', -2),, ), description = "叮叮当，叮叮当，铃儿响叮当~摇起来会发出悦耳的铃音，不过还是盖不住呻吟声。"),
                            Item(name = '乳贴', target = 'girl', type = IT_Dress, pic=random.choice([ '乳贴.webp']), template = True, rank = 2, max_rank = 6, rarity = 3, price = 1800 effects = (Effect('change', 'libido', 6), Effect('change', 'sensitivity', 6), Effect('change', 'obedience', 6), Effect('change', 'constitution', 6), Effect('change', 'defense', -2),, ), description = "各种款式的贴纸，紧紧的粘在乳首，撕下来的时候别有一番快感。"),
                            Item(name = '泡泡', target = 'girl', type = IT_Dress, pic=random.choice([ '泡泡.webp']), template = True, rank = 2, max_rank = 6, rarity = 3, price = 2000 effects = (Effect('change', 'service', 6), Effect('change', 'sex', 6), Effect('change', 'anal', 6), Effect('change', 'fetish', 6), , Effect('change', 'defense', -2),, ), description = "用特质肥皂搓出来的泡泡，覆盖在身体表面，和她一起洗个澡吧。"),
                            Item(name = '淫纹', target = 'girl', type = IT_Dress, pic=random.choice([ '防具.webp']), template = True, rank = 3, max_rank = 6, rarity = 4, price = 2400 effects = (Effect('change', 'beauty', 6), Effect('change', 'charm', 6), Effect('change', 'refinement', 6), Effect('change', 'body', 6), Effect('change', 'libido', 6), Effect('change', 'sensitivity', 6), Effect('change', 'obedience', 6), Effect('change', 'constitution', 6), Effect('change', 'service', 6), Effect('change', 'sex', 6), Effect('change', 'anal', 6), Effect('change', 'fetish', 6), Effect('special', 'lucky', 1), ), description = "古老而又神秘的纹章，能够赐予女孩魅魔的加护，征服他们吧！"),
                            
                            Item(name = '运动服', target = 'girl', type = IT_Dress, pic=random.choice([ '运动服.webp']), template = True, rank = 1, max_rank = 6, rarity = 1, price = 600 effects = (Effect('change', 'defense', 1),, ), description = "穿上它就有了运动的动力，当汗水浸透衣服时会露出底下健美的身体"),
                            Item(name = '防具', target = 'girl', type = IT_Dress, pic=random.choice([ '淫纹.webp']), template = True, rank = 1, max_rank = 6, rarity = 2, price = 1000 effects = (Effect('change', 'defense', 2),, ), description = "兼具防护性能和舒适度的贴身防护制服，在冒险者之中也很流行。"),

                            ]


        # Generate variable quality items
        # all_items += generate_template_items(template_items)

        for it in template_items:
            for i in range(0,7):
                if it.min_rank <= i <= it.max_rank:
                    all_items.append(it.generate_new_item(i))

        item_dict = {it.name : it for it in all_items}

    return
