# 内容扩展 V1.0
## 91Panda 制作 2025-2-15
## 适用于青楼之王0.3版本



init 900 python:


    config.label_overrides["init_postings"] = "Panda_init_postings"

    ExtraPanda_template = Mod(
        
                ## 模组基础信息 (注意: 版本号将用于检查模组是否是最新版本。 Failure to update the version number may lead to broken mods and saved games)
                name = "内容扩展",
                folder = "ExtraPanda",
                creator = "PANDA",
                version = 1.0,
                pic = "封面.png",
                description = """公会提高了工作效率，扩建了大厅，现在这里有更多的委托和培训课程可供选择。\n本模组仅扩展了文本内容，并无属性改动。""",

                ## 事件字典 (所有的模组事件都应该在这里设置)
                )

    # 添加新的任务和课程  

label Panda_init_postings():

    python:

        # 任务委托 #

        quest_templates = [
            
            #原版任务#
                        Quest("quest", name = '平面模特' main_stat = 'Beauty', second_stat = 'Libido', other_stats = ("Body", "Charm", "Refinement"), tags = 'model', description = random.choice(["I'm an artist, an artist I tell thee! I need a muse. Clothing unnecessary."]), sound = s_sigh),
                        Quest("quest", name = '招募舞伴' main_stat = 'Body', second_stat = 'Constitution', other_stats = ("Beauty", "Charm", "Refinement"), tags = 'dance', description = random.choice(["Looking for a private, intimate dance...."]), sound = s_sigh),
                        Quest("quest", name = '宴会准备' main_stat = 'Charm', second_stat = 'Obedience', other_stats = ("Beauty", "Body", "Refinement"), tags = 'waitress', description = random.choice(["My guests are arriving soon, and nothing is ready! This is a disaster! I need your help!"]), sound = s_sigh),
                        Quest("quest", name = '临时女伴' main_stat = 'Refinement', second_stat = 'Sensitivity', other_stats = ("Beauty", "Body", "Charm"), tags = 'geisha', description = random.choice(["I have an important guild meeting, and I need to show them I'm not just anyone. Looking for an elite companion to impress those snobs."]), sound = s_sigh),
                        Quest("quest", name = '枯木逢春' main_stat = 'Libido', second_stat = 'Sensitivity', other_stats = ("Beauty", "Body", "Refinement"), tags = 'sex', description = random.choice(["It's been many a moon since lil' willy's gone to sleep. I need a girl to help me remember what it was like in the old days..."]), sound = s_aaha),
                        Quest("quest", name = '突破记录' main_stat = 'Constitution', second_stat = 'Libido', other_stats = ("Body", "Charm", "Refinement"), tags = 'anal', description = random.choice(["I aim to break the record set by Long Dick Silver, and this will take long hours of practice... Help me get harder and stronger so that I can succeed!"]), sound = s_aaha),
                        Quest("quest", name = '租赁女友' main_stat = 'Sensitivity', second_stat = 'Obedience', other_stats = ("Beauty", "Charm", "Refinement"), tags = 'service', description = random.choice(["I feel lonely... Will you help me forget my troubles?"]), sound = s_aaha),
                        Quest("quest", name = '家政清洁' main_stat = 'Obedience', second_stat = 'Constitution', other_stats = ("Beauty", "Body", "Charm"), tags = 'maid', description = random.choice(["I need an extra maid to help out in the mansion. There is a very specific uniform..."]), sound = s_aaha),
                        Quest("quest", name = '家庭教师' main_stat = 'Service', second_stat = 'Sex', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'service', description = random.choice(["My son is already 21, and not yet married. He's a big oaf when it comes to women... Can you help him come out of his shell?"]), sound = s_mmmh),
                        Quest("quest", name = '寻欢作乐' main_stat = 'Sex', second_stat = 'Anal', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'sex', description = random.choice(["I'm stranded here, drinking ale all day at the local inn. I'm bored out of my mind. Please send me some 'entertainment'."]), sound = s_mmmh),
                        Quest("quest", name = '赏菊大会' main_stat = 'Anal', second_stat = 'Fetish', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'anal', description = random.choice(["The men don't know, but the little girls understand..."]), sound = s_mmmh),
                        Quest("quest", name = '地牢之夜' main_stat = 'Fetish', second_stat = 'Service', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'fetish', description = random.choice(["Looking for partners to help us test our new contraption. C'mon! It will be fun!"]), sound = s_mmmh),
                        Quest("quest", name = '狂欢派对' main_stat = 'Constitution', second_stat = 'Libido', other_stats = ("Body", "Charm", "Refinement"), tags = 'group', description = random.choice(["Hosting a large delegation at my house. We need girls to entertain our guests in every way possible..."]), sound = s_aah),
                        Quest("quest", name = '群芳争艳' main_stat = 'Service', second_stat = 'Sex', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'group', description = random.choice(["We are holding our traditional 'ladies night' at our local guild hall. Looking for a girl to play with a friend in front of the audience..."]), sound = s_aah),
                        
            #扩展任务#            
                        Quest("quest", name = 'Model needed' main_stat = 'Beauty', second_stat = 'Libido', other_stats = ("Body", "Charm", "Refinement"), tags = 'model', description = random.choice(["I'm an artist, an artist I tell thee! I need a muse. Clothing unnecessary."]), sound = s_sigh),
                        Quest("quest", name = 'Private dance' main_stat = 'Body', second_stat = 'Constitution', other_stats = ("Beauty", "Charm", "Refinement"), tags = 'dance', description = random.choice(["Looking for a private, intimate dance...."]), sound = s_sigh),
                        Quest("quest", name = 'Entertain my guests' main_stat = 'Charm', second_stat = 'Obedience', other_stats = ("Beauty", "Body", "Refinement"), tags = 'waitress', description = random.choice(["My guests are arriving soon, and nothing is ready! This is a disaster! I need your help!"]), sound = s_sigh),
                        Quest("quest", name = 'Escort needed' main_stat = 'Refinement', second_stat = 'Sensitivity', other_stats = ("Beauty", "Body", "Charm"), tags = 'geisha', description = random.choice(["I have an important guild meeting, and I need to show them I'm not just anyone. Looking for an elite companion to impress those snobs."]), sound = s_sigh),
                        Quest("quest", name = 'Make me feel young again' main_stat = 'Libido', second_stat = 'Sensitivity', other_stats = ("Beauty", "Body", "Refinement"), tags = 'sex', description = random.choice(["It's been many a moon since lil' willy's gone to sleep. I need a girl to help me remember what it was like in the old days..."]), sound = s_aaha),
                        Quest("quest", name = 'Setting a record' main_stat = 'Constitution', second_stat = 'Libido', other_stats = ("Body", "Charm", "Refinement"), tags = 'anal', description = random.choice(["I aim to break the record set by Long Dick Silver, and this will take long hours of practice... Help me get harder and stronger so that I can succeed!"]), sound = s_aaha),
                        Quest("quest", name = 'Girlfriend needed' main_stat = 'Sensitivity', second_stat = 'Obedience', other_stats = ("Beauty", "Charm", "Refinement"), tags = 'service', description = random.choice(["I feel lonely... Will you help me forget my troubles?"]), sound = s_aaha),
                        Quest("quest", name = 'Hiring help' main_stat = 'Obedience', second_stat = 'Constitution', other_stats = ("Beauty", "Body", "Charm"), tags = 'maid', description = random.choice(["I need an extra maid to help out in the mansion. There is a very specific uniform..."]), sound = s_aaha),
                        Quest("quest", name = 'Please teach my son' main_stat = 'Service', second_stat = 'Sex', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'service', description = random.choice(["My son is already 21, and not yet married. He's a big oaf when it comes to women... Can you help him come out of his shell?"]), sound = s_mmmh),
                        Quest("quest", name = 'Bored in Zan' main_stat = 'Sex', second_stat = 'Anal', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'sex', description = random.choice(["I'm stranded here, drinking ale all day at the local inn. I'm bored out of my mind. Please send me some 'entertainment'."]), sound = s_mmmh),
                        Quest("quest", name = 'Back door man' main_stat = 'Anal', second_stat = 'Fetish', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'anal', description = random.choice(["The men don't know, but the little girls understand..."]), sound = s_mmmh),
                        Quest("quest", name = 'Night at the dungeon' main_stat = 'Fetish', second_stat = 'Service', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'fetish', description = random.choice(["Looking for partners to help us test our new contraption. C'mon! It will be fun!"]), sound = s_mmmh),
                        Quest("quest", name = 'Private party' main_stat = 'Constitution', second_stat = 'Libido', other_stats = ("Body", "Charm", "Refinement"), tags = 'group', description = random.choice(["Hosting a large delegation at my house. We need girls to entertain our guests in every way possible..."]), sound = s_aah),
                        Quest("quest", name = 'Ladies night' main_stat = 'Service', second_stat = 'Sex', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'group', description = random.choice(["We are holding our traditional 'ladies night' at our local guild hall. Looking for a girl to play with a friend in front of the audience..."]), sound = s_aah),
                        
                        Quest("quest", name = 'Model needed' main_stat = 'Beauty', second_stat = 'Libido', other_stats = ("Body", "Charm", "Refinement"), tags = 'model', description = random.choice(["I'm an artist, an artist I tell thee! I need a muse. Clothing unnecessary."]), sound = s_sigh),
                        Quest("quest", name = 'Private dance' main_stat = 'Body', second_stat = 'Constitution', other_stats = ("Beauty", "Charm", "Refinement"), tags = 'dance', description = random.choice(["Looking for a private, intimate dance...."]), sound = s_sigh),
                        Quest("quest", name = 'Entertain my guests' main_stat = 'Charm', second_stat = 'Obedience', other_stats = ("Beauty", "Body", "Refinement"), tags = 'waitress', description = random.choice(["My guests are arriving soon, and nothing is ready! This is a disaster! I need your help!"]), sound = s_sigh),
                        Quest("quest", name = 'Escort needed' main_stat = 'Refinement', second_stat = 'Sensitivity', other_stats = ("Beauty", "Body", "Charm"), tags = 'geisha', description = random.choice(["I have an important guild meeting, and I need to show them I'm not just anyone. Looking for an elite companion to impress those snobs."]), sound = s_sigh),
                        Quest("quest", name = 'Make me feel young again' main_stat = 'Libido', second_stat = 'Sensitivity', other_stats = ("Beauty", "Body", "Refinement"), tags = 'sex', description = random.choice(["It's been many a moon since lil' willy's gone to sleep. I need a girl to help me remember what it was like in the old days..."]), sound = s_aaha),
                        Quest("quest", name = 'Setting a record' main_stat = 'Constitution', second_stat = 'Libido', other_stats = ("Body", "Charm", "Refinement"), tags = 'anal', description = random.choice(["I aim to break the record set by Long Dick Silver, and this will take long hours of practice... Help me get harder and stronger so that I can succeed!"]), sound = s_aaha),
                        Quest("quest", name = 'Girlfriend needed' main_stat = 'Sensitivity', second_stat = 'Obedience', other_stats = ("Beauty", "Charm", "Refinement"), tags = 'service', description = random.choice(["I feel lonely... Will you help me forget my troubles?"]), sound = s_aaha),
                        Quest("quest", name = 'Hiring help' main_stat = 'Obedience', second_stat = 'Constitution', other_stats = ("Beauty", "Body", "Charm"), tags = 'maid', description = random.choice(["I need an extra maid to help out in the mansion. There is a very specific uniform..."]), sound = s_aaha),
                        Quest("quest", name = 'Please teach my son' main_stat = 'Service', second_stat = 'Sex', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'service', description = random.choice(["My son is already 21, and not yet married. He's a big oaf when it comes to women... Can you help him come out of his shell?"]), sound = s_mmmh),
                        Quest("quest", name = 'Bored in Zan' main_stat = 'Sex', second_stat = 'Anal', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'sex', description = random.choice(["I'm stranded here, drinking ale all day at the local inn. I'm bored out of my mind. Please send me some 'entertainment'."]), sound = s_mmmh),
                        Quest("quest", name = 'Back door man' main_stat = 'Anal', second_stat = 'Fetish', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'anal', description = random.choice(["The men don't know, but the little girls understand..."]), sound = s_mmmh),
                        Quest("quest", name = 'Night at the dungeon' main_stat = 'Fetish', second_stat = 'Service', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'fetish', description = random.choice(["Looking for partners to help us test our new contraption. C'mon! It will be fun!"]), sound = s_mmmh),
                        Quest("quest", name = 'Private party' main_stat = 'Constitution', second_stat = 'Libido', other_stats = ("Body", "Charm", "Refinement"), tags = 'group', description = random.choice(["Hosting a large delegation at my house. We need girls to entertain our guests in every way possible..."]), sound = s_aah),
                        Quest("quest", name = 'Ladies night' main_stat = 'Service', second_stat = 'Sex', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'group', description = random.choice(["We are holding our traditional 'ladies night' at our local guild hall. Looking for a girl to play with a friend in front of the audience..."]), sound = s_aah),
                        
                        
                        ]

        # 培训课程 #

        #原版课程#
        class_templates = [
                            Quest("class", name = 'Modeling' main_stat = 'Beauty', second_stat = 'Libido', other_stats = ("Body", "Charm", "Refinement"), tags = 'model', description = random.choice(["Learn the secrets to looking fabulous and have perfect hair at all times! Who wants to look natural anyway?"]), sound = s_sigh),
                            Quest("class", name = 'Dancing' main_stat = 'Body', second_stat = 'Constitution', other_stats = ("Beauty", "Charm", "Refinement"), tags = 'dance', description = random.choice(["Zomba! Bodyfighting! Aqua reggeaton!\nHurry before we make up even more silly names!"]), sound = s_sigh),
                            Quest("class", name = 'Waitress{#1}' main_stat = 'Charm', second_stat = 'Obedience', other_stats = ("Beauty", "Body", "Refinement"), tags = 'waitress', description = random.choice(["Learn the basics of working tables... You'll never spill a glass on a customer's crotch again, unless you want to!"]), sound = s_sigh),
                            Quest("class", name = 'Geisha{#1}' main_stat = 'Refinement', second_stat = 'Sensitivity', other_stats = ("Beauty", "Body", "Charm"), tags = 'geisha', description = random.choice(["Master all Zanic traditional arts, including the exact science of tea ceremony trigonometry. Don't look like an ass because your tea cup is off 5 degrees to the left!"]), sound = s_sigh),
                            Quest("class", name = 'Massage' main_stat = 'Libido', second_stat = 'Sensitivity', other_stats = ("Beauty", "Body", "Refinement"), tags = 'masseuse', description = random.choice(["Spend a relaxing few days at the spa with us. It will be awesome! As for the teaching... Wait, what teaching?"]), sound = s_aaha),
                            Quest("class", name = 'Swimming' main_stat = 'Constitution', second_stat = 'Libido', other_stats = ("Body", "Charm", "Refinement"), tags = 'swim', description = random.choice(["The sun shining on exposed bodies... Water running along voluptuous curves... Tanning oil on glistening skin... And swimming, of course. Erm."]), sound = s_aaha),
                            Quest("class", name = 'Singing' main_stat = 'Sensitivity', second_stat = 'Obedience', other_stats = ("Beauty", "Charm", "Refinement"), tags = 'sing', description = random.choice(["'Sing properly dammit, or I'll rip off your head and shove manure down your neck!'. How bad can a singing class be? Oh, you'll see..."]), sound = s_aaha),
                            Quest("class", name = 'Maid' main_stat = 'Obedience', second_stat = 'Constitution', other_stats = ("Beauty", "Body", "Charm"), tags = 'maid', description = random.choice(["'If you want to clean up properly, you have to bend forward a lot more! More... More... Hmm, that's better.'"]), sound = s_aaha),
                            Quest("class", name = 'XXX{#1}' main_stat = 'Service', second_stat = 'Sex', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'XXX', description = random.choice(["Learn to pleasure a man... Or a woman, if you're so inclined. Why not learn both?{#1}"]), sound = s_aah),
                            Quest("class", name = 'XXX' main_stat = 'Sex', second_stat = 'Anal', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'XXX', description = random.choice(["Learn to pleasure a man... Or a woman, if you're so inclined. Why not learn both?"]), sound = s_aah),
                            Quest("class", name = 'Hardcore{#1}' main_stat = 'Anal', second_stat = 'Fetish', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'hardcore', description = random.choice(["We've got more tools than a hardware store, more beasts than the palace zoo... And by the time we're finished, they're all gonna fit inside of her!{#1}"]), sound = s_scream),
                            Quest("class", name = 'Hardcore{#2}' main_stat = 'Fetish', second_stat = 'Service', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'hardcore', description = random.choice(["We've got more tools than a hardware store, more beasts than the palace zoo... And by the time we're finished, they're all gonna fit inside of her!"]), sound = s_scream),
                            
        #扩展课程#                    
                            Quest("class", name = 'Modeling' main_stat = 'Beauty', second_stat = 'Libido', other_stats = ("Body", "Charm", "Refinement"), tags = 'model', description = random.choice(["Learn the secrets to looking fabulous and have perfect hair at all times! Who wants to look natural anyway?"]), sound = s_sigh),
                            Quest("class", name = 'Dancing' main_stat = 'Body', second_stat = 'Constitution', other_stats = ("Beauty", "Charm", "Refinement"), tags = 'dance', description = random.choice(["Zomba! Bodyfighting! Aqua reggeaton!\nHurry before we make up even more silly names!"]), sound = s_sigh),
                            Quest("class", name = 'Waitress{#1}' main_stat = 'Charm', second_stat = 'Obedience', other_stats = ("Beauty", "Body", "Refinement"), tags = 'waitress', description = random.choice(["Learn the basics of working tables... You'll never spill a glass on a customer's crotch again, unless you want to!"]), sound = s_sigh),
                            Quest("class", name = 'Geisha{#1}' main_stat = 'Refinement', second_stat = 'Sensitivity', other_stats = ("Beauty", "Body", "Charm"), tags = 'geisha', description = random.choice(["Master all Zanic traditional arts, including the exact science of tea ceremony trigonometry. Don't look like an ass because your tea cup is off 5 degrees to the left!"]), sound = s_sigh),
                            Quest("class", name = 'Massage' main_stat = 'Libido', second_stat = 'Sensitivity', other_stats = ("Beauty", "Body", "Refinement"), tags = 'masseuse', description = random.choice(["Spend a relaxing few days at the spa with us. It will be awesome! As for the teaching... Wait, what teaching?"]), sound = s_aaha),
                            Quest("class", name = 'Swimming' main_stat = 'Constitution', second_stat = 'Libido', other_stats = ("Body", "Charm", "Refinement"), tags = 'swim', description = random.choice(["The sun shining on exposed bodies... Water running along voluptuous curves... Tanning oil on glistening skin... And swimming, of course. Erm."]), sound = s_aaha),
                            Quest("class", name = 'Singing' main_stat = 'Sensitivity', second_stat = 'Obedience', other_stats = ("Beauty", "Charm", "Refinement"), tags = 'sing', description = random.choice(["'Sing properly dammit, or I'll rip off your head and shove manure down your neck!'. How bad can a singing class be? Oh, you'll see..."]), sound = s_aaha),
                            Quest("class", name = 'Maid' main_stat = 'Obedience', second_stat = 'Constitution', other_stats = ("Beauty", "Body", "Charm"), tags = 'maid', description = random.choice(["'If you want to clean up properly, you have to bend forward a lot more! More... More... Hmm, that's better.'"]), sound = s_aaha),
                            Quest("class", name = 'XXX{#1}' main_stat = 'Service', second_stat = 'Sex', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'XXX', description = random.choice(["Learn to pleasure a man... Or a woman, if you're so inclined. Why not learn both?{#1}"]), sound = s_aah),
                            Quest("class", name = 'XXX' main_stat = 'Sex', second_stat = 'Anal', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'XXX', description = random.choice(["Learn to pleasure a man... Or a woman, if you're so inclined. Why not learn both?"]), sound = s_aah),
                            Quest("class", name = 'Hardcore{#1}' main_stat = 'Anal', second_stat = 'Fetish', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'hardcore', description = random.choice(["We've got more tools than a hardware store, more beasts than the palace zoo... And by the time we're finished, they're all gonna fit inside of her!{#1}"]), sound = s_scream),
                            Quest("class", name = 'Hardcore{#2}' main_stat = 'Fetish', second_stat = 'Service', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'hardcore', description = random.choice(["We've got more tools than a hardware store, more beasts than the palace zoo... And by the time we're finished, they're all gonna fit inside of her!"]), sound = s_scream),                            
                            
                            
                            Quest("class", name = 'Modeling' main_stat = 'Beauty', second_stat = 'Libido', other_stats = ("Body", "Charm", "Refinement"), tags = 'model', description = random.choice(["Learn the secrets to looking fabulous and have perfect hair at all times! Who wants to look natural anyway?"]), sound = s_sigh),
                            Quest("class", name = 'Dancing' main_stat = 'Body', second_stat = 'Constitution', other_stats = ("Beauty", "Charm", "Refinement"), tags = 'dance', description = random.choice(["Zomba! Bodyfighting! Aqua reggeaton!\nHurry before we make up even more silly names!"]), sound = s_sigh),
                            Quest("class", name = 'Waitress{#1}' main_stat = 'Charm', second_stat = 'Obedience', other_stats = ("Beauty", "Body", "Refinement"), tags = 'waitress', description = random.choice(["Learn the basics of working tables... You'll never spill a glass on a customer's crotch again, unless you want to!"]), sound = s_sigh),
                            Quest("class", name = 'Geisha{#1}' main_stat = 'Refinement', second_stat = 'Sensitivity', other_stats = ("Beauty", "Body", "Charm"), tags = 'geisha', description = random.choice(["Master all Zanic traditional arts, including the exact science of tea ceremony trigonometry. Don't look like an ass because your tea cup is off 5 degrees to the left!"]), sound = s_sigh),
                            Quest("class", name = 'Massage' main_stat = 'Libido', second_stat = 'Sensitivity', other_stats = ("Beauty", "Body", "Refinement"), tags = 'masseuse', description = random.choice(["Spend a relaxing few days at the spa with us. It will be awesome! As for the teaching... Wait, what teaching?"]), sound = s_aaha),
                            Quest("class", name = 'Swimming' main_stat = 'Constitution', second_stat = 'Libido', other_stats = ("Body", "Charm", "Refinement"), tags = 'swim', description = random.choice(["The sun shining on exposed bodies... Water running along voluptuous curves... Tanning oil on glistening skin... And swimming, of course. Erm."]), sound = s_aaha),
                            Quest("class", name = 'Singing' main_stat = 'Sensitivity', second_stat = 'Obedience', other_stats = ("Beauty", "Charm", "Refinement"), tags = 'sing', description = random.choice(["'Sing properly dammit, or I'll rip off your head and shove manure down your neck!'. How bad can a singing class be? Oh, you'll see..."]), sound = s_aaha),
                            Quest("class", name = 'Maid' main_stat = 'Obedience', second_stat = 'Constitution', other_stats = ("Beauty", "Body", "Charm"), tags = 'maid', description = random.choice(["'If you want to clean up properly, you have to bend forward a lot more! More... More... Hmm, that's better.'"]), sound = s_aaha),
                            Quest("class", name = 'XXX{#1}' main_stat = 'Service', second_stat = 'Sex', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'XXX', description = random.choice(["Learn to pleasure a man... Or a woman, if you're so inclined. Why not learn both?{#1}"]), sound = s_aah),
                            Quest("class", name = 'XXX' main_stat = 'Sex', second_stat = 'Anal', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'XXX', description = random.choice(["Learn to pleasure a man... Or a woman, if you're so inclined. Why not learn both?"]), sound = s_aah),
                            Quest("class", name = 'Hardcore{#1}' main_stat = 'Anal', second_stat = 'Fetish', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'hardcore', description = random.choice(["We've got more tools than a hardware store, more beasts than the palace zoo... And by the time we're finished, they're all gonna fit inside of her!{#1}"]), sound = s_scream),
                            Quest("class", name = 'Hardcore{#2}' main_stat = 'Fetish', second_stat = 'Service', other_stats = ("Libido", "Constitution", "Obedience", "Sensitivity"), tags = 'hardcore', description = random.choice(["We've got more tools than a hardware store, more beasts than the palace zoo... And by the time we're finished, they're all gonna fit inside of her!"]), sound = s_scream),                            
                            
                            
                            ]

    return
